# -*- coding: utf-8 -*-
"""
Módulo de Configuração
======================

Contém configurações globais e prompts do sistema.
"""

from .settings import (
    APP_NAME,
    APP_VERSION,
    APP_TAGLINE,
    MODEL_NAME,
    MODEL_REFINEMENT,
    MODEL_ADVANCED,
    get_openai_client,
    is_gpt5_model,
    get_model_config,
    # Parâmetros GPT-4
    GENERATION_TEMPERATURE,
    REFINEMENT_TEMPERATURE,
    REVIEW_TEMPERATURE,
    MAX_TOKENS_GENERATION,
    MAX_TOKENS_REVIEW,
    # Parâmetros GPT-5
    REASONING_EFFORT_GENERATION,
    REASONING_EFFORT_REFINEMENT,
    REASONING_EFFORT_REVIEW,
    VERBOSITY_GENERATION,
    VERBOSITY_REFINEMENT,
    VERBOSITY_REVIEW,
    MAX_OUTPUT_TOKENS_GENERATION,
    MAX_OUTPUT_TOKENS_REFINEMENT,
    MAX_OUTPUT_TOKENS_REVIEW,
)

from .prompts import (
    PROMPT_NORMAL,
    PROMPT_HARD,
    REFINE_PROMPT,
    PROMPT_AUDIT,
    PROMPT_FINAL_REVIEW,
)

__all__ = [
    "APP_NAME",
    "APP_VERSION", 
    "APP_TAGLINE",
    "MODEL_NAME",
    "MODEL_REFINEMENT",
    "MODEL_ADVANCED",
    "get_openai_client",
    "is_gpt5_model",
    "get_model_config",
    "PROMPT_NORMAL",
    "PROMPT_HARD",
    "REFINE_PROMPT",
    "PROMPT_AUDIT",
    "PROMPT_FINAL_REVIEW",
    # Parâmetros GPT-4
    "GENERATION_TEMPERATURE",
    "REFINEMENT_TEMPERATURE",
    "REVIEW_TEMPERATURE",
    "MAX_TOKENS_GENERATION",
    "MAX_TOKENS_REVIEW",
    # Parâmetros GPT-5
    "REASONING_EFFORT_GENERATION",
    "REASONING_EFFORT_REFINEMENT",
    "REASONING_EFFORT_REVIEW",
    "VERBOSITY_GENERATION",
    "VERBOSITY_REFINEMENT",
    "VERBOSITY_REVIEW",
    "MAX_OUTPUT_TOKENS_GENERATION",
    "MAX_OUTPUT_TOKENS_REFINEMENT",
    "MAX_OUTPUT_TOKENS_REVIEW",
]
